---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-service-config
  labels:
    config: library
data:
  REACT_APP_BACKEND_API_URL: http://libservice:8000/api/v1
  REACT_APP_BOOKS_API_URL: http://libservice:8000/api/v1/books